--[[
Copyright (C) 2012-2014 Spacebuild Development Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
]]--

med_bridges = {
  "models/spacebuild/medbridge.mdl",
  "models/spacebuild/medbridge2.mdl",
  "models/slyfo/cruisercockpit.mdl",
  "models/slyfo/combat_cockpit_small.mdl",
  "models/slyfo/cockpit_smround.mdl",
  "models/slyfo/sidecockpit.mdl",
  "models/slyfo/sccleft.mdl",
  "models/slyfo/sccright.mdl",
  "models/slyfo/capturehull1.mdl",
  "models/spacebuild/medbridge2_angularbridge.mdl",
  "models/spacebuild/medbridge2_longbridge.mdl",
  "models/spacebuild/medbridge2_twolevel.mdl",
  "models/slyfo/cockpit_lground.mdl",
  "models/slyfo/cockpit_sideround.mdl",
  "models/spacebuild/medbridge2_360view_doublebridge.mdl",
  "models/spacebuild/medbridge2_midsectionbridge.mdl",
  "models/spacebuild/medbridge2_midsection_doublebridge.mdl",
  "models/spacebuild/medbridge2_midsection_doublebridge2.mdl",
  "models/spacebuild/nova/supercarrierbridge.mdl",
  "models/slyfo/thcockpit.mdl",
}

med_carrier_deck = {
  "models/slyfo/cdeck_bow.mdl",
  "models/slyfo/cdeck_back.mdl",
  "models/slyfo/cdeck_single.mdl",
  "models/slyfo/cdeck_tjoint.mdl",
  "models/slyfo/cdeck_double.mdl",
  "models/slyfo/cdeck_doublewide.mdl",
  "models/slyfo/cdeck_doublewideconv.mdl",
}

med_doubles = {
  "models/spacebuild/medbridge2_enginehull2.mdl",
  "models/spacebuild/medbridge2_enginehull.mdl",
  "models/spacebuild/medbridge2_enginehull4.mdl",
  "models/slyfo/matthewenginelong.mdl",
  "models/slyfo/matthewengineshort.mdl",
  "models/slyfo/gallant_class_engine3.mdl",
  "models/slyfo/gallant_class_engine4.mdl",
  "models/slyfo/gallant_class_engine6.mdl",
  "models/spacebuild/medbridge2_enginedoublehull_flaps.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_narrow.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_wide.mdl",
  "models/slyfo/fishfacemki.mdl",
  "models/slyfo/gallant_class_engine1.mdl",
  "models/slyfo/gallant_class_engine2.mdl",
  "models/slyfo/gallant_class_engine5.mdl",
  "models/spacebuild/nova/supercarrierbridge.mdl",
  "models/spacebuild/medbridge2_engineaddon1.mdl",
  "models/spacebuild/medbridge2_enginehull3.mdl",
  "models/spacebuild/medbridge2_large_solar_sail.mdl",
}

med_engines = {
  "models/spacebuild/medbridge2_enginehull2.mdl",
  "models/spacebuild/medbridge2_enginehull.mdl",
  "models/spacebuild/medbridge2_enginehull4.mdl",
  "models/slyfo/matthewenginelong.mdl",
  "models/slyfo/matthewengineshort.mdl",
  "models/slyfo/gallant_class_engine3.mdl",
  "models/slyfo/gallant_class_engine4.mdl",
  "models/slyfo/gallant_class_engine6.mdl",
  "models/spacebuild/medbridge2_enginedoublehull_flaps.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_narrow.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_wide.mdl",
  "models/slyfo/fishfacemki.mdl",
  "models/slyfo/gallant_class_engine1.mdl",
  "models/slyfo/gallant_class_engine2.mdl",
  "models/slyfo/gallant_class_engine5.mdl",
  "models/spacebuild/nova/supercarrierbridge.mdl",
  "models/spacebuild/medbridge2_engineaddon1.mdl",
  "models/spacebuild/medbridge2_enginehull3.mdl",
  "models/spacebuild/medbridge2_large_solar_sail.mdl",
}

med_entry = {
  "models/slyfo/doublehatch.mdl",
  "models/slyfo/doublehatch_hatch.mdl",
  "models/slyfo/bottomless.mdl",
  "models/slyfo/topless.mdl",
  "models/slyfo/topless_top.mdl",
  "models/slyfo/foldcargobaseplate.mdl",
  "models/slyfo/foldcargohatch.mdl",
  "models/slyfo/inversebay.mdl",
  "models/slyfo/inversebayhatch.mdl",
  "models/slyfo/mcpdropbay.mdl",
  "models/slyfo/mcpdropbayhatch.mdl",
  "models/slyfo/mcpdropglass.mdl",
  "models/spacebuild/nova/hull_lift1.mdl",
  "models/spacebuild/nova/hull_lift1lift.mdl",
  "models/spacebuild/nova/hull_lift_double.mdl",
  "models/spacebuild/nova/hull_lift_doublelift.mdl",
}

med_hangers = {
  "models/slyfo/shangar.mdl",
  "models/slyfo/doublesideopen.mdl",
  "models/slyfo/minelayer.mdl",
  "models/slyfo/longhangar.mdl",
  "models/spacebuild/medbridge2_fighterbay.mdl",
  "models/spacebuild/medbridge2_fighterbay_noglass.mdl",
  "models/spacebuild/medbridge2_fighterbayshortcap.mdl",
  "models/spacebuild/medbridge2_fighterbayshortcap2.mdl",
  "models/slyfo/hangar1.mdl",
  "models/spacebuild/medbridge2_fighterbay2.mdl",
  "models/spacebuild/medbridge2_fighterbay2_noglass.mdl",
  "models/spacebuild/medbridge2_fighterbay2longcap.mdl",
  "models/slyfo/hangar2.mdl",
  "models/slyfo/hangar3.mdl",
  "models/spacebuild/medbridge2_fighterbay3a.mdl",
  "models/spacebuild/medbridge2_fighterbay3.mdl",
  "models/spacebuild/medbridge2_fighterbay3transcap.mdl",
  "models/spacebuild/medbridge2_fighterbay3sidebaycap.mdl",
  "models/slyfo/thhangar.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_elevator.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_guardrail.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_crosswalk.mdl",
  "models/spacebuild/medbridge2_doublehull_elevatorpad.mdl",
  "models/spacebuild/medbridge2_doublehull_elevatorclamp.mdl",
}

med_misc = {
  "models/spacebuild/medbridge2_topplate.mdl",
  "models/spacebuild/medbridge2_topplatebendcap.mdl",
  "models/slyfo/biodome.mdl",
  "models/slyfo/biodome2.mdl",
  "models/slyfo/evilsphere.mdl",
  "models/slyfo/capturehull1.mdl",
  "models/slyfo/cargocap.mdl",
  "models/slyfo/cargocapglass.mdl",
  "models/slyfo/cargocaplight.mdl",
  "models/slyfo/cargoclosed.mdl",
  "models/slyfo/cargoopen.mdl",
  "models/slyfo/cargosideopen.mdl",
  "models/slyfo/cargosideopenhatch.mdl",
  "models/slyfo/cargostack.mdl",
  "models/slyfo/cargohub.mdl",
  "models/slyfo/consolescreenbig.mdl",
  "models/slyfo/consolescreenmed.mdl",
  "models/slyfo/consolescreensmall.mdl",
  "models/slyfo/doublehatch.mdl",
  "models/slyfo/doublehatch_hatch.mdl",
  "models/slyfo/barricade.mdl",
  "models/slyfo/finfunnel.mdl",
  "models/slyfo/powercrystal.mdl",
  "models/slyfo/t-eng.mdl",
  "models/slyfo/boxpallet.mdl",
  "models/slyfo/boxpallet2.mdl",
  "models/slyfo/flatpallet.mdl",
  "models/slyfo/forkbase.mdl",
  "models/slyfo/forklift.mdl",
  "models/slyfo/forkrobot.mdl",
  "models/spacebuild/nova/drop_pod.mdl",
  "models/slyfo/probe1.mdl",
  "models/slyfo/probe2.mdl",
}

med_singles = {
  "models/spacebuild/medbridge2_emptyhull.mdl",
  "models/spacebuild/medbridge2_emptyhull_90.mdl",
  "models/spacebuild/medbridge2_emptyhull_t.mdl",
  "models/spacebuild/medbridge2_emptyhull_x.mdl",
  "models/spacebuild/medbridge2_widey.mdl",
  "models/spacebuild/medbridge2_compflathull.mdl",
  "models/spacebuild/medbridge2_stacksinglehull_openbottom.mdl",
  "models/spacebuild/medbridge2_stacksinglehull_ramp.mdl",
  "models/spacebuild/medbridge2_stacksinglehull_roof.mdl",
  "models/spacebuild/medbridge2_flatcap.mdl",
  "models/spacebuild/medbridge2_s128cap.mdl",
  "models/spacebuild/doorway_invert.mdl",
  "models/slyfo/straighthull.mdl",
  "models/slyfo/inverter.mdl",
  "models/slyfo/doubletrilong.mdl",
  "models/slyfo/doubletrishort.mdl",
  "models/slyfo/largetri.mdl",
  "models/slyfo/smalltri.mdl",
  "models/slyfo/ljoint.mdl",
  "models/slyfo/tjoint.mdl",
  "models/slyfo/xjoint.mdl",
  "models/slyfo/trit.mdl",
  "models/slyfo/turnabout.mdl",
  "models/slyfo/largerad.mdl",
  "models/slyfo/triangularhub.mdl",
  "models/slyfo/dwbent.mdl",
  "models/slyfo/dwbump.mdl",
  "models/slyfo/dwsmooth.mdl",
  "models/slyfo/longlass.mdl",
  "models/slyfo/longnoglass.mdl",
  "models/slyfo/mednoglass.mdl",
  "models/slyfo/medglass.mdl",
  "models/slyfo/shortnoglass.mdl",
  "models/slyfo/shortglass.mdl",
  "models/slyfo/bottomless.mdl",
  "models/slyfo/topless.mdl",
  "models/slyfo/topless_top.mdl",
  "models/slyfo/angledown.mdl",
  "models/slyfo/angleup.mdl",
  "models/slyfo/ramp.mdl",
  "models/slyfo/rampleft.mdl",
  "models/slyfo/rampright.mdl",
  "models/slyfo/tramp.mdl",
  "models/slyfo/xramp.mdl",
  "models/slyfo/tramptriple.mdl",
  "models/slyfo/tramptripleinv.mdl",
  "models/slyfo/doublehatch.mdl",
  "models/slyfo/doublehatch_hatch.mdl",
}
med_triples = {
  "models/slyfo/thhull.mdl",
  "models/slyfo/thlong.mdl",
  "models/slyfo/thnoramp.mdl",
  "models/slyfo/thramp.mdl",
  "models/slyfo/thcockpit.mdl",
  "models/slyfo/thhangar.mdl",
}


mod_accessories = {
  "models/cerus/modbridge/misc/accessories/acc_ant2_red.mdl",
  "models/cerus/modbridge/misc/accessories/acc_ant_red.mdl",
  "models/cerus/modbridge/misc/accessories/acc_furnace1.mdl",
  "models/cerus/modbridge/misc/accessories/acc_radar1.mdl",
  "models/cerus/modbridge/misc/engines/eng_sq11b.mdl",
}

mod_cockpits_bridges_and_glass_corridors = {
  "models/cerus/modbridge/core/g-111wd.mdl",
  "models/cerus/modbridge/core/g-211s.mdl",
  "models/cerus/modbridge/core/g-221s.mdl",
  "models/cerus/modbridge/core/g-231s.mdl",
  "models/cerus/modbridge/core/bridgeg-211.mdl",
  "models/cerus/modbridge/core/g-221.mdl",
  "models/cerus/modbridge/core/g-231w.mdl",
  "models/cerus/modbridge/core/g-231r.mdl",
  "models/cerus/modbridge/core/sc-111g.mdl",
  "models/cerus/modbridge/core/s-111g.mdl",
  "models/cerus/modbridge/core/s-221g.mdl",
  "models/cerus/modbridge/core/s-331g.mdl",
  "models/cerus/modbridge/core/sc-131g2.mdl",
  "models/cerus/modbridge/core/sc-131g3.mdl",
  "models/cerus/modbridge/core/sc-131g.mdl",
}

mod_corridor_segments = {
  "models/cerus/modbridge/core/s-111.mdl",
  "models/cerus/modbridge/core/s-211.mdl",
  "models/cerus/modbridge/core/s-311.mdl",
  "models/cerus/modbridge/core/sc-111.mdl",
  "models/cerus/modbridge/core/c-111.mdl",
  "models/cerus/modbridge/core/t-111.mdl",
  "models/cerus/modbridge/core/x-111.mdl",
  "models/cerus/modbridge/core/s-121.mdl",
  "models/cerus/modbridge/core/s-221.mdl",
  "models/cerus/modbridge/core/s-321.mdl",
  "models/cerus/modbridge/core/sc121.mdl",
  "models/cerus/modbridge/core/c-21.mdl",
  "models/cerus/modbridge/core/t-21.mdl",
  "models/cerus/modbridge/core/x-21.mdl",
  "models/cerus/modbridge/core/s-131.mdl",
  "models/cerus/modbridge/core/s-231.mdl",
  "models/cerus/modbridge/core/s-331.mdl",
  "models/cerus/modbridge/core/sc-131.mdl",
  "models/cerus/modbridge/core/c-331.mdl",
  "models/cerus/modbridge/core/t-331.mdl",
  "models/cerus/modbridge/core/x-331.mdl",
  "models/cerus/modbridge/core/s-332.mdl",
  "models/cerus/modbridge/core/sc-332.mdl",
  "models/cerus/modbridge/core/c-332.mdl",
  "models/cerus/modbridge/core/t-332.mdl",
  "models/cerus/modbridge/core/x-332.mdl",
}

mod_corvette_fighters = {
  "models/cerus/mcorvette/bridge1.mdl",
  "models/cerus/mcorvette/body1.mdl",
  "models/cerus/mcorvette/pod1-r.mdl",
  "models/cerus/mcorvette/pod1-l.mdl",
  "models/cerus/fighters/wraith.mdl",
  "models/cerus/fighters/stingray.mdl",
}

mod_elevators = {
  "models/cerus/modbridge/misc/elevator/eb111.mdl",
  "models/cerus/modbridge/misc/elevator/eb332.mdl",
  "models/cerus/modbridge/misc/elevator/ecb111.mdl",
  "models/cerus/modbridge/misc/elevator/ecm111.mdl",
  "models/cerus/modbridge/misc/elevator/ect111.mdl",
  "models/cerus/modbridge/misc/elevator/elev_111.mdl",
  "models/cerus/modbridge/misc/elevator/elev_332.mdl",
  "models/cerus/modbridge/misc/elevator/elev_332b.mdl",
  "models/cerus/modbridge/misc/elevator/em111.mdl",
  "models/cerus/modbridge/misc/elevator/em332.mdl",
  "models/cerus/modbridge/misc/elevator/et111.mdl",
  "models/cerus/modbridge/misc/elevator/et332.mdl",
  "models/cerus/modbridge/misc/elevator/etm111.mdl",
  "models/cerus/modbridge/misc/elevator/etm111g.mdl",
  "models/cerus/modbridge/misc/elevator/etm112.mdl",
  "models/cerus/modbridge/misc/elevator/etm113.mdl",
  "models/cerus/modbridge/misc/elevator/etm113g.mdl",
  "models/cerus/modbridge/misc/elevator/se11f.mdl",
  "models/cerus/modbridge/core/s-331eb.mdl",
  "models/cerus/modbridge/core/s-331em.mdl",
  "models/cerus/modbridge/core/s-331et.mdl",
  "models/cerus/modbridge/core/s-332ep.mdl",
}

mod_engines_weapons_prefabs_and_dorrs = {
  "models/cerus/modbridge/misc/engines/eng_sq11b.mdl",
  "models/cerus/modbridge/misc/weapons/wep_ion1.mdl",
  "models/cerus/modbridge/core/prefab/crew_331.mdl",
  "models/cerus/modbridge/misc/doors/door11b.mdl",
  "models/cerus/modbridge/misc/doors/door11a.mdl",
  "models/cerus/modbridge/misc/doors/door12a.mdl",
  "models/cerus/modbridge/misc/doors/door13a.mdl",
  "models/cerus/modbridge/misc/doors/door23a.mdl",
  "models/cerus/modbridge/misc/doors/door33a.mdl",
}

mod_external_decor = {
  "models/cerus/modbridge/plate/bp111wd.mdl",
  "models/cerus/modbridge/plate/bp111wd2.mdl",
  "models/cerus/modbridge/plate/bp211.mdl",
  "models/cerus/modbridge/plate/bp211s.mdl",
  "models/cerus/modbridge/plate/bp221.mdl",
  "models/cerus/modbridge/plate/bp221s.mdl",
  "models/cerus/modbridge/plate/bp231g.mdl",
  "models/cerus/modbridge/plate/bp231s.mdl",
  "models/cerus/modbridge/plate/bp231w.mdl",
  "models/cerus/modbridge/plate/flat/acc112.mdl",
  "models/cerus/modbridge/plate/flat/ace312.mdl",
  "models/cerus/modbridge/plate/flat/acw213-2.mdl",
  "models/cerus/modbridge/plate/flat/acw213.mdl",
  "models/cerus/modbridge/plate/flat/acw313.mdl",
  "models/cerus/modbridge/plate/flat/b111.mdl",
  "models/cerus/modbridge/plate/flat/b121.mdl",
  "models/cerus/modbridge/plate/flat/b131.mdl",
  "models/cerus/modbridge/plate/flat/b221.mdl",
  "models/cerus/modbridge/plate/flat/b231.mdl",
  "models/cerus/modbridge/plate/flat/b331.mdl",
  "models/cerus/modbridge/plate/flat/cv-s11.mdl",
  "models/cerus/modbridge/plate/flat/cv-sts11.mdl",
  "models/cerus/modbridge/plate/flat/cv-wt11s.mdl",
  "models/cerus/modbridge/plate/flat/pc111.mdl",
  "models/cerus/modbridge/plate/flat/rp312.mdl",
  "models/cerus/modbridge/plate/flat/rp322.mdl",
  "models/cerus/modbridge/plate/flat/rp332.mdl",
  "models/cerus/modbridge/plate/flat/rpf312.mdl",
  "models/cerus/modbridge/plate/flat/rpf322.mdl",
  "models/cerus/modbridge/plate/flat/rpf332.mdl",
  "models/cerus/modbridge/plate/flat/rs21l.mdl",
  "models/cerus/modbridge/plate/flat/rs21r.mdl",
  "models/cerus/modbridge/plate/flat/rsc23.mdl",
  "models/cerus/modbridge/plate/flat/rsc32l.mdl",
  "models/cerus/modbridge/plate/flat/rsc32r.mdl",
  "models/cerus/modbridge/plate/flat/rsc33.mdl",
  "models/cerus/modbridge/plate/flat/rsr23.mdl",
  "models/cerus/modbridge/plate/flat/s11.mdl",
  "models/cerus/modbridge/plate/flat/s11g.mdl",
  "models/cerus/modbridge/plate/flat/s11g2.mdl",
  "models/cerus/modbridge/plate/flat/s21.mdl",
  "models/cerus/modbridge/plate/flat/s22.mdl",
  "models/cerus/modbridge/plate/flat/s31.mdl",
  "models/cerus/modbridge/plate/flat/s31g.mdl",
  "models/cerus/modbridge/plate/flat/s32.mdl",
  "models/cerus/modbridge/plate/flat/s33.mdl",
  "models/cerus/modbridge/plate/flat/st111.mdl",
  "models/cerus/modbridge/plate/flat/st121.mdl",
  "models/cerus/modbridge/plate/flat/st131.mdl",
  "models/cerus/modbridge/plate/flat/stw111.mdl",
  "models/cerus/modbridge/plate/flat/t32.mdl",
  "models/cerus/modbridge/plate/flat/w111.mdl",
  "models/cerus/modbridge/plate/flat/w121.mdl",
  "models/cerus/modbridge/plate/flat/w131.mdl",
  "models/cerus/modbridge/plate/flat/w311.mdl",
  "models/cerus/modbridge/plate/flat/w321.mdl",
  "models/cerus/modbridge/plate/flat/w331.mdl",
  "models/cerus/modbridge/plate/flat/wc311.mdl",
  "models/cerus/modbridge/plate/flat/wd11.mdl",
  "models/cerus/modbridge/plate/flat/wd21.mdl",
  "models/cerus/modbridge/plate/flat/wd31.mdl",
  "models/cerus/modbridge/plate/flat/wdc11.mdl",
  "models/cerus/modbridge/plate/flat/wdc11b.mdl",
  "models/cerus/modbridge/plate/flat/wde11.mdl",
  "models/cerus/modbridge/plate/flat/wde21.mdl",
  "models/cerus/modbridge/plate/flat/wde31.mdl",
  "models/cerus/modbridge/plate/flat/wr311.mdl",
  "models/cerus/modbridge/plate/flat/wr321.mdl",
  "models/cerus/modbridge/plate/flat/wr331.mdl",
  "models/cerus/modbridge/plate/flat/ws311.mdl",
  "models/cerus/modbridge/plate/flat/wsc311.mdl",
  "models/cerus/modbridge/plate/flat/wsc311cl.mdl",
  "models/cerus/modbridge/plate/flat/wsc311cr.mdl",
  "models/cerus/modbridge/plate/flat/wsc441.mdl",
  "models/cerus/modbridge/plate/flat/wsp311l.mdl",
  "models/cerus/modbridge/plate/flat/wsp311r.mdl",
  "models/cerus/modbridge/plate/flat/wt111.mdl",
  "models/cerus/modbridge/plate/flat/wt121.mdl",
  "models/cerus/modbridge/plate/flat/wt131.mdl",
}

mod_height_transfer = {
  "models/cerus/modbridge/core/r-312.mdl",
  "models/cerus/modbridge/core/rs-312.mdl",
  "models/cerus/modbridge/core/rst-312.mdl",
  "models/cerus/modbridge/core/rs-322.mdl",
  "models/cerus/modbridge/core/rst-322l.mdl",
  "models/cerus/modbridge/core/rst-322r.mdl",
  "models/cerus/modbridge/core/rs-332.mdl",
  "models/cerus/modbridge/core/rst-332.mdl",
  "models/cerus/modbridge/core/rst-332c.mdl",
  "models/cerus/modbridge/core/rso-332f.mdl",
  "models/cerus/modbridge/core/rst-332cf.mdl",
  "models/cerus/modbridge/core/rst-332f.mdl",
}

mod_spartan = {
  "models/cerus/modbridge/core/spartan/s-111.mdl",
  "models/cerus/modbridge/core/spartan/s-211.mdl",
  "models/cerus/modbridge/core/spartan/s-311.mdl",
  "models/cerus/modbridge/core/spartan/c-111.mdl",
  "models/cerus/modbridge/core/spartan/s-121.mdl",
  "models/cerus/modbridge/core/spartan/s-221.mdl",
  "models/cerus/modbridge/core/spartan/s-321.mdl",
  "models/cerus/modbridge/core/spartan/c-221.mdl",
  "models/cerus/modbridge/core/spartan/s-131.mdl",
  "models/cerus/modbridge/core/spartan/s-231.mdl",
  "models/cerus/modbridge/core/spartan/s-331.mdl",
  "models/cerus/modbridge/core/spartan/cv-11-31.mdl",
}

mod_splitter = {
  "models/cerus/modbridge/core/tc-131.mdl",
  "models/cerus/modbridge/core/t-131.mdl",
  "models/cerus/modbridge/core/c-131r.mdl",
  "models/cerus/modbridge/core/c-131l.mdl",
  "models/cerus/modbridge/core/cv-11-21.mdl",
  "models/cerus/modbridge/core/cv-11-31.mdl",
  "models/cerus/modbridge/core/cv-21-31.mdl",
  "models/cerus/modbridge/core/cvw-11-31.mdl",
  "models/cerus/modbridge/core/cv-mb-smb.mdl",
  "models/cerus/modbridge/core/rso-312.mdl",
  "models/cerus/modbridge/core/rso-322.mdl",
  "models/cerus/modbridge/core/rso-332.mdl",
}


other_sbep_community = {
  "models/sbep_community/d12airscrubber.mdl",
  "models/sbep_community/d12console.mdl",
  "models/sbep_community/d12consolert.mdl",
  "models/sbep_community/d12consolescreen.mdl",
  "models/sbep_community/d12flakcannon.mdl",
  "models/sbep_community/d12fusionbomb.mdl",
  "models/sbep_community/d12guidedbomb.mdl",
  "models/sbep_community/d12mbdstairs.mdl",
  "models/sbep_community/d12medflak.mdl",
  "models/sbep_community/d12proxmine.mdl",
  "models/sbep_community/d12shieldemitter.mdl",
  "models/sbep_community/d12siesmiccharge.mdl",
  "models/sbep_community/d12singengine.mdl",
  "models/sbep_community/xwingbl.mdl",
  "models/sbep_community/xwingbody.mdl",
  "models/sbep_community/xwingbr.mdl",
  "models/sbep_community/xwinggunbl.mdl",
  "models/sbep_community/xwinggunbr.mdl",
  "models/sbep_community/xwingguntl.mdl",
  "models/sbep_community/xwingguntr.mdl",
  "models/sbep_community/xwingtl.mdl",
  "models/sbep_community/xwingtr.mdl",
  "models/sbep_community/ywing.mdl",
}


sbmp_fighters = {
  "models/slyfo/sword.mdl",
  "models/spacebuild/light_combat_corvette.mdl",
  "models/slyfo/transportlarge.mdl",
  "models/slyfo/transportsmall.mdl",
  "models/slyfo/torpedoship1.mdl",
  "models/slyfo/torpedoship2.mdl",
  "models/slyfo/shuttle.mdl",
  "models/slyfo/shuttlehatchclosed.mdl",
  "models/slyfo/shuttlehatchopen.mdl",
  "models/spacebuild/dronefighter_1.mdl",
  "models/spacebuild/milcock.mdl",
  "models/spacebuild/milcock2_redux.mdl",
  "models/spacebuild/milcock3_redux.mdl",
  "models/spacebuild/milcock4a.mdl",
  "models/spacebuild/milcock4b.mdl",
  "models/spacebuild/emount1_milcock4.mdl",
  "models/spacebuild/emount4_fighter.mdl",
  "models/spacebuild/milcock5a.mdl",
  "models/spacebuild/emount3_milcock6.mdl",
  "models/spacebuild/milcock6_redux.mdl",
  "models/spacebuild/milcock6_emount1.mdl",
  "models/spacebuild/milcock7_emount1.mdl",
  "models/spacebuild/milcock7_emount2.mdl",
  "models/spacebuild/mil_cock_7.mdl",
  "models/spacebuild/milcock8.mdl",
  "models/slyfo/jetenginelg.mdl",
  "models/slyfo/jetenginelg_mounted.mdl",
  "models/slyfo/jetenginemed.mdl",
  "models/slyfo/jetenginemed_mounted.mdl",
  "models/slyfo/jetenginesml.mdl",
  "models/slyfo/jetenginesml_mounted.mdl",
  "models/slyfo/nacshortsleft.mdl",
  "models/slyfo/nacshortsright.mdl",
  "models/slyfo/nacshuttleleft.mdl",
  "models/slyfo/nacshuttleright.mdl",
  "models/slyfo/nactngleft.mdl",
  "models/slyfo/nactngright.mdl",
  "models/slyfo/rex1peice.mdl",
  "models/slyfo/rexbottom.mdl",
  "models/slyfo/rextop.mdl",
  "models/slyfo/spbarlg.mdl",
  "models/slyfo/spbarmed.mdl",
  "models/slyfo/spbarsml.mdl",
  "models/slyfo/t-eng.mdl",
  "models/slyfo/tenginelg.mdl",
  "models/slyfo/tenginemed.mdl",
  "models/slyfo/tenginesm.mdl",
  "models/slyfo/winglg.mdl",
  "models/slyfo/winglg_jetleft.mdl",
  "models/slyfo/winglg_jetright.mdl",
  "models/slyfo/wingmed.mdl",
  "models/slyfo/wingmed_jetleft.mdl",
  "models/slyfo/wingmed_jetright.mdl",
  "models/slyfo/wingsml.mdl",
  "models/slyfo/wingsml_jetleft.mdl",
  "models/slyfo/wingsml_jetright.mdl",
  "models/spacebuild/milcock4_multipod1.mdl",
  "models/spacebuild/milcock4_wing1.mdl",
  "models/spacebuild/milcock4_wing2.mdl",
  "models/spacebuild/milcock4_wing3.mdl",
  "models/spacebuild/milcock4_wing4.mdl",
  "models/spacebuild/milcock4_wing5l.mdl",
  "models/spacebuild/milcock4_wing5r.mdl",
  "models/spacebuild/milcock4_wing6.mdl",
  "models/spacebuild/milcock4_wing7.mdl",
  "models/spacebuild/medbridge2_gatling_cannon.mdl",
  "models/spacebuild/nova/flak1.mdl",
  "models/slyfo/swordgatleft.mdl",
  "models/slyfo/swordgatmid.mdl",
  "models/slyfo/swordgatright.mdl",
  "models/spacebuild/medbridge2_missile_launcher.mdl",
  "models/slyfo/swordgrenade.mdl",
  "models/slyfo/mcpcannon.mdl",
  "models/slyfo/subrocket.mdl",
  "models/spacebuild/cannon1_gen.mdl",
  "models/slyfo/goldfish.mdl",
  "models/slyfo/torpedo.mdl",
  "models/slyfo/torpedo2.mdl",
  "models/slyfo/warhead.mdl",
}

sbmp_freighters = {
  "models/slyfo/cargoship.mdl",
  "models/slyfo/cargoshiphatch.mdl",
  "models/slyfo/frigate1.mdl",
  "models/slyfo/frigate1ramp.mdl",
  "models/spacebuild/medbridge.mdl",
  "models/slyfo/ccockpit.mdl",
  "models/slyfo/carrierbay.mdl",
  "models/slyfo/doublecarrier.mdl",
  "models/slyfo/carriersplit.mdl",
  "models/slyfo/cengine.mdl",
  "models/slyfo/fhatch.mdl",
}

sbmp_ship_modules = {
    "models/spacebuild/chair.mdl",
    "models/spacebuild/chair2.mdl",
    "models/spacebuild/emount1_milcock4.mdl",
    "models/spacebuild/emount2_milcock4.mdl",
    "models/spacebuild/emount3_milcock6.mdl",
    "models/spacebuild/emount4_fighter.mdl",
    "models/spacebuild/medbridge.mdl",
    "models/spacebuild/medbridge2.mdl",
    "models/spacebuild/medbridge2_emptydoublehull.mdl",
    "models/spacebuild/medbridge2_emptydoublehull_decktodeckramp.mdl",
    "models/spacebuild/medbridge2_emptyhull.mdl",
    "models/spacebuild/medbridge2_emptyhull_90.mdl",
    "models/spacebuild/medbridge2_emptyhull_t.mdl",
    "models/spacebuild/medbridge2_emptyhull_x.mdl",
    "models/spacebuild/medbridge2_enginehull.mdl",
    "models/spacebuild/medbridge2_enginehull2.mdl",
    "models/spacebuild/medbridge2_enginehull3.mdl",
    "models/spacebuild/medbridge2_fighterbay.mdl",
    "models/spacebuild/medbridge2_fighterbay2.mdl",
    "models/spacebuild/medbridge2_fighterbay2longcap.mdl",
    "models/spacebuild/medbridge2_fighterbay2_noglass.mdl",
    "models/spacebuild/medbridge2_fighterbay3.mdl",
    "models/spacebuild/medbridge2_fighterbay3a.mdl",
    "models/spacebuild/medbridge2_fighterbay3sidebaycap.mdl",
    "models/spacebuild/medbridge2_fighterbay3transcap.mdl",
    "models/spacebuild/medbridge2_fighterbayshortcap.mdl",
    "models/spacebuild/medbridge2_fighterbayshortcap2.mdl",
    "models/spacebuild/medbridge2_fighterbay_noglass.mdl",
    "models/spacebuild/medbridge2_flatcap.mdl",
    "models/spacebuild/medbridge2_s128cap.mdl",
    "models/spacebuild/medbridge2_singletodoublehull.mdl",
    "models/spacebuild/medbridge2_twolevel.mdl",
    "models/spacebuild/medbridge2_widey.mdl",
    "models/spacebuild/milcock.mdl",
    "models/spacebuild/milcock4a.mdl",
    "models/spacebuild/milcock4b.mdl",
    "models/spacebuild/milcock4_multipod1.mdl",
    "models/spacebuild/milcock4_wing1.mdl",
    "models/spacebuild/milcock4_wing2.mdl",
    "models/spacebuild/milcock4_wing3.mdl",
    "models/spacebuild/milcock4_wing4.mdl",
    "models/spacebuild/milcock4_wing5l.mdl",
    "models/spacebuild/milcock4_wing5r.mdl",
    "models/spacebuild/milcock4_wing6.mdl",
    "models/spacebuild/milcock4_wing7.mdl",
    "models/spacebuild/milcock5a.mdl",
    "models/spacebuild/dronefighter_1.mdl",
    "models/spacebuild/medbridge2_360view_doublebridge.mdl",
    "models/spacebuild/medbridge2_doublehull_hanger_crosswalk.mdl",
    "models/spacebuild/medbridge2_doublehull_hanger_elevator.mdl",
    "models/spacebuild/medbridge2_doublehull_hanger_guardrail.mdl",
    "models/spacebuild/medbridge2_enginedoublehull2_narrow.mdl",
    "models/spacebuild/medbridge2_enginedoublehull2_wide.mdl",
    "models/spacebuild/medbridge2_enginedoublehull_flaps.mdl",
    "models/spacebuild/medbridge2_doublehull_centralcolumnelevatorpad.mdl",
    "models/spacebuild/medbridge2_enginehull4.mdl",
    "models/spacebuild/medbridge2_midsection_doublebridge2.mdl",
    "models/spacebuild/medbridge2_stackdoublehull_ramp.mdl",
    "models/spacebuild/medbridge2_stackdoublehull.mdl",
    "models/spacebuild/medbridge2_stacksinglehull_openbottom.mdl",
    "models/spacebuild/medbridge2_stacksinglehull_ramp.mdl",
    "models/spacebuild/medbridge2_stacksinglehull_roof.mdl",
 }

sbmp_slyfo = {
  "models/slyfo/carrierbay.mdl",
  "models/slyfo/carriersplit.mdl",
  "models/slyfo/ccockpit.mdl",
  "models/slyfo/cengine.mdl",
  "models/slyfo/doublecarrier.mdl",
  "models/slyfo/hub2.mdl",
  "models/slyfo/inverter.mdl",
  "models/slyfo/turnabout.mdl",
  "models/slyfo/subrocket.mdl",
  "models/slyfo/angledown.mdl",
  "models/slyfo/angleup.mdl",
  "models/slyfo/doubletrilong.mdl",
  "models/slyfo/doubletrishort.mdl",
  "models/slyfo/largetri.mdl",
  "models/slyfo/ramp.mdl",
  "models/slyfo/shangar.mdl",
  "models/slyfo/smalltri.mdl",
  "models/slyfo/straighthull.mdl",
  "models/slyfo/trit.mdl",
  "models/slyfo/doublehull.mdl",
  "models/slyfo/smallrad.mdl",
  "models/slyfo/largerad.mdl",
  "models/slyfo/triangularhub.mdl",
  "models/slyfo/tjoint.mdl",
  "models/slyfo/tjointdouble.mdl",
  "models/slyfo/xjoint.mdl",
  "models/slyfo/xjointdouble.mdl",
  "models/slyfo/shuttle.mdl",
  "models/slyfo/shuttlehatchclosed.mdl",
  "models/slyfo/shuttlehatchopen.mdl",
  "models/slyfo/rex1peice.mdl",
  "models/slyfo/rexbottom.mdl",
  "models/slyfo/rextop.mdl",
  "models/slyfo/dwbent.mdl",
  "models/slyfo/dwbump.mdl",
  "models/slyfo/dwsmooth.mdl",
  "models/slyfo/longhangar.mdl",
  "models/slyfo/thcockpit.mdl",
  "models/slyfo/thhangar.mdl",
  "models/slyfo/thhull.mdl",
  "models/slyfo/thlong.mdl",
  "models/slyfo/thnoramp.mdl",
  "models/slyfo/thramp.mdl",
  "models/slyfo/sidecockpit.mdl",
  "models/slyfo/tramp.mdl",
  "models/slyfo/trampdouble.mdl",
  "models/slyfo/tramptriple.mdl",
  "models/slyfo/tramptripleinv.mdl",
  "models/slyfo/xramp.mdl",
  "models/slyfo/xrampdouble.mdl",
  "models/slyfo/rampleft.mdl",
  "models/slyfo/rampright.mdl",
  "models/slyfo/cruisercockpit.mdl",
  "models/slyfo/longlass.mdl",
  "models/slyfo/longnoglass.mdl",
  "models/slyfo/medglass.mdl",
  "models/slyfo/mednoglass.mdl",
  "models/slyfo/shortglass.mdl",
  "models/slyfo/shortnoglass.mdl",
  "models/slyfo/doublehullramp.mdl",
  "models/slyfo/inversebay.mdl",
  "models/slyfo/inversebayhatch.mdl",
  "models/slyfo/mcp.mdl",
  "models/slyfo/mcpcannon.mdl",
  "models/slyfo/mcphatch.mdl",
  "models/slyfo/mcphatchglass.mdl",
  "models/slyfo/mcpskid.mdl",
  "models/slyfo/sccleft.mdl",
  "models/slyfo/sccright.mdl",
  "models/slyfo/unbendable.mdl",
  "models/slyfo/mcpdropbayhatch.mdl",
  "models/slyfo/nacshortsleft.mdl",
  "models/slyfo/nacshortsright.mdl",
  "models/slyfo/nacshuttleleft.mdl",
  "models/slyfo/nacshuttleright.mdl",
  "models/slyfo/nactngleft.mdl",
  "models/slyfo/nactngright.mdl",
  "models/slyfo/t-eng.mdl",
  "models/slyfo/mcpdropbay.mdl",
  "models/slyfo/consolescreenbig.mdl",
  "models/slyfo/consolescreenmed.mdl",
  "models/slyfo/consolescreensmall.mdl",
  "models/slyfo/matthewenginelong.mdl",
  "models/slyfo/matthewengineshort.mdl",
  "models/slyfo/walldoorleft.mdl",
  "models/slyfo/walldoorright.mdl",
  "models/slyfo/walllong.mdl",
  "models/slyfo/walllonggate.mdl",
  "models/slyfo/wallshort.mdl",
  "models/slyfo/wallshortgate.mdl",
  "models/slyfo/barricade.mdl",
  "models/slyfo/capturehull1.mdl",
  "models/slyfo/frigate1.mdl",
  "models/slyfo/cargostack.mdl",
  "models/slyfo/artycannon.mdl",
  "models/slyfo/cargocap.mdl",
  "models/slyfo/mcpcannon.mdl",
  "models/slyfo/cargohub.mdl",
  "models/slyfo/cargocapglass.mdl",
  "models/slyfo/cargocaplight.mdl",
  "models/slyfo/cargoclosed.mdl",
  "models/slyfo/cargoopen.mdl",
  "models/slyfo/cargosideopen.mdl",
  "models/slyfo/cargoshiphatch.mdl",
  "models/slyfo/cargoship.mdl",
  "models/slyfo/fhatch.mdl",
  "models/slyfo/unbendable.mdl",
  "models/slyfo/smlmissilepod.mdl",
  "models/slyfo/smlturretbase.mdl",
  "models/slyfo/smlturrettop.mdl",
  "models/slyfo/wheelcycle.mdl",
  "models/slyfo/torpedo.mdl",
  "models/slyfo/swordgatleft.mdl",
  "models/slyfo/swordgatright.mdl",
  "models/slyfo/swordgrenade.mdl",
  "models/slyfo/boxpallet.mdl",
  "models/slyfo/flatpallet.mdl",
  "models/slyfo/torpedo2.mdl",
  "models/slyfo/warhead.mdl",
  "models/slyfo/goldfish.mdl",
}

sbmp_weapons = {
  "models/spacebuild/nova/med-mac2.mdl",
  "models/spacebuild/nova/med-mac2_1.mdl",
  "models/spacebuild/nova/machuge.mdl",
  "models/spacebuild/nova/macbig.mdl",
  "models/slyfo/swordgatleft.mdl",
  "models/slyfo/swordgatmid.mdl",
  "models/slyfo/swordgatright.mdl",
  "models/spacebuild/medbridge2_gatling_cannon.mdl",
  "models/spacebuild/nova/flak1.mdl",
  "models/slyfo/swordgrenade.mdl",
  "models/spacebuild/medbridge2_missile_launcher.mdl",
  "models/slyfo/artycannon.mdl",
  "models/slyfo/mcpcannon.mdl",
  "models/slyfo/subrocket.mdl",
  "models/spacebuild/cannon1_gen.mdl",
  "models/slyfo/powercrystal.mdl",
  "models/slyfo/finfunnel.mdl",
  "models/slyfo/smlmissilepod.mdl",
  "models/slyfo/smlturrettop.mdl",
  "models/slyfo/smlturretbase.mdl",
  "models/slyfo/goldfish.mdl",
  "models/slyfo/spacemine.mdl",
  "models/slyfo/torpedo.mdl",
  "models/slyfo/torpedo2.mdl",
  "models/slyfo/warhead.mdl",
}


smb_elevators_large = {
  "models/smallbridge/elevators_large/sblelevb.mdl",
  "models/smallbridge/elevators_large/sblelevbe.mdl",
  "models/smallbridge/elevators_large/sblelevbedh.mdl",
  "models/smallbridge/elevators_large/sblelevbr.mdl",
  "models/smallbridge/elevators_large/sblelevbt.mdl",
  "models/smallbridge/elevators_large/sblelevbx.mdl",
  "models/smallbridge/elevators_large/sblelevm.mdl",
  "models/smallbridge/elevators_large/sblelevme.mdl",
  "models/smallbridge/elevators_large/sblelevmedh.mdl",
  "models/smallbridge/elevators_large/sblelevmr.mdl",
  "models/smallbridge/elevators_large/sblelevmt.mdl",
  "models/smallbridge/elevators_large/sblelevmx.mdl",
  "models/smallbridge/elevators_large/sblelevp0.mdl",
  "models/smallbridge/elevators_large/sblelevp1.mdl",
  "models/smallbridge/elevators_large/sblelevp2e.mdl",
  "models/smallbridge/elevators_large/sblelevp2r.mdl",
  "models/smallbridge/elevators_large/sblelevp3.mdl",
  "models/smallbridge/elevators_large/sblelevs.mdl",
  "models/smallbridge/elevators_large/sblelevs2.mdl",
  "models/smallbridge/elevators_large/sblelevt.mdl",
  "models/smallbridge/elevators_large/sblelevte.mdl",
  "models/smallbridge/elevators_large/sblelevtedh.mdl",
  "models/smallbridge/elevators_large/sblelevtr.mdl",
  "models/smallbridge/elevators_large/sblelevtt.mdl",
  "models/smallbridge/elevators_large/sblelevtx.mdl",
}

smb_elevators_small = {
  "models/smallbridge/elevators_small/sbselevb.mdl",
  "models/smallbridge/elevators_small/sbselevbe.mdl",
  "models/smallbridge/elevators_small/sbselevbedh.mdl",
  "models/smallbridge/elevators_small/sbselevbedw.mdl",
  "models/smallbridge/elevators_small/sbselevbr.mdl",
  "models/smallbridge/elevators_small/sbselevbt.mdl",
  "models/smallbridge/elevators_small/sbselevbx.mdl",
  "models/smallbridge/elevators_small/sbselevm.mdl",
  "models/smallbridge/elevators_small/sbselevme.mdl",
  "models/smallbridge/elevators_small/sbselevmedh.mdl",
  "models/smallbridge/elevators_small/sbselevmedw.mdl",
  "models/smallbridge/elevators_small/sbselevmr.mdl",
  "models/smallbridge/elevators_small/sbselevmt.mdl",
  "models/smallbridge/elevators_small/sbselevmx.mdl",
  "models/smallbridge/elevators_small/sbselevp0.mdl",
  "models/smallbridge/elevators_small/sbselevp1.mdl",
  "models/smallbridge/elevators_small/sbselevp2e.mdl",
  "models/smallbridge/elevators_small/sbselevp2esl.mdl",
  "models/smallbridge/elevators_small/sbselevp2r.mdl",
  "models/smallbridge/elevators_small/sbselevp3.mdl",
  "models/smallbridge/elevators_small/sbselevs.mdl",
  "models/smallbridge/elevators_small/sbselevs2.mdl",
  "models/smallbridge/elevators_small/sbselevslant.mdl",
  "models/smallbridge/elevators_small/sbselevt.mdl",
  "models/smallbridge/elevators_small/sbselevte.mdl",
  "models/smallbridge/elevators_small/sbselevtedh.mdl",
  "models/smallbridge/elevators_small/sbselevtedw.mdl",
  "models/smallbridge/elevators_small/sbselevtr.mdl",
  "models/smallbridge/elevators_small/sbselevtt.mdl",
  "models/smallbridge/elevators_small/sbselevtx.mdl",
}

smb_height_transfer = {
  "models/smallbridge/height transfer/sbhtcramp.mdl",
  "models/smallbridge/height transfer/sbhtcramp2d.mdl",
  "models/smallbridge/height transfer/sbhtcramp2u.mdl",
  "models/smallbridge/height transfer/sbhtcrampdl.mdl",
  "models/smallbridge/height transfer/sbhtramp.mdl",
  "models/smallbridge/height transfer/sbhtramp05.mdl",
  "models/smallbridge/height transfer/sbhtrampdw.mdl",
  "models/smallbridge/height transfer/sbhtrampdw05.mdl",
  "models/smallbridge/height transfer/sbhtsdwrampd.mdl",
  "models/smallbridge/height transfer/sbhtsdwrampm.mdl",
  "models/smallbridge/height transfer/sbhtsdwrampu.mdl",
  "models/smallbridge/height transfer/sbhtsrampd.mdl",
  "models/smallbridge/height transfer/sbhtsrampm.mdl",
  "models/smallbridge/height transfer/sbhtsrampu.mdl",
  "models/smallbridge/height transfer/sbhtsrampz.mdl",
  "models/smallbridge/height transfer/sbhtsrampzdh.mdl",
  "models/smallbridge/height transfer/sbhtsrampzdw.mdl",
  "models/smallbridge/height transfer/sbhtsrampzdwdh.mdl",
}

smb_hulls_dw = {
  "models/smallbridge/hulls_dw/sbhulldwe05.mdl",
  "models/smallbridge/hulls_dw/sbhulldwe1.mdl",
  "models/smallbridge/hulls_dw/sbhulldwe2.mdl",
  "models/smallbridge/hulls_dw/sbhulldwe3.mdl",
  "models/smallbridge/hulls_dw/sbhulldwe4.mdl",
  "models/smallbridge/hulls_dw/sbhulldwedh.mdl",
  "models/smallbridge/hulls_dw/sbhulldwedh05.mdl",
  "models/smallbridge/hulls_dw/sbhulldwedh2.mdl",
  "models/smallbridge/hulls_dw/sbhulldwedh3.mdl",
  "models/smallbridge/hulls_dw/sbhulldwedh4.mdl",
  "models/smallbridge/hulls_dw/sbhulldweflip.mdl",
  "models/smallbridge/hulls_dw/sbhulldwend.mdl",
  "models/smallbridge/hulls_dw/sbhulldwend2.mdl",
  "models/smallbridge/hulls_dw/sbhulldwenddh.mdl",
  "models/smallbridge/hulls_dw/sbhulldwenddh2.mdl",
  "models/smallbridge/hulls_dw/sbhulldwr.mdl",
  "models/smallbridge/hulls_dw/sbhulldwrdh.mdl",
  "models/smallbridge/hulls_dw/sbhulldwt.mdl",
  "models/smallbridge/hulls_dw/sbhulldwtdh.mdl",
  "models/smallbridge/hulls_dw/sbhulldwtdl.mdl",
  "models/smallbridge/hulls_dw/sbhulldwtsl.mdl",
  "models/smallbridge/hulls_dw/sbhulldwx.mdl",
  "models/smallbridge/hulls_dw/sbhulldwxdh.mdl",
  "models/smallbridge/hulls_dw/sbhulldwxdl.mdl",
}

smb_hulls_sw = {
  "models/smallbridge/hulls_sw/sbhullcurvel.mdl",
  "models/smallbridge/hulls_sw/sbhullcurvem.mdl",
  "models/smallbridge/hulls_sw/sbhullcurves.mdl",
  "models/smallbridge/hulls_sw/sbhulle05.mdl",
  "models/smallbridge/hulls_sw/sbhulle1.mdl",
  "models/smallbridge/hulls_sw/sbhulle2.mdl",
  "models/smallbridge/hulls_sw/sbhulle3.mdl",
  "models/smallbridge/hulls_sw/sbhulle4.mdl",
  "models/smallbridge/hulls_sw/sbhulledh.mdl",
  "models/smallbridge/hulls_sw/sbhulledh05.mdl",
  "models/smallbridge/hulls_sw/sbhulledh2.mdl",
  "models/smallbridge/hulls_sw/sbhulledh3.mdl",
  "models/smallbridge/hulls_sw/sbhulledh4.mdl",
  "models/smallbridge/hulls_sw/sbhulleflip.mdl",
  "models/smallbridge/hulls_sw/sbhullend.mdl",
  "models/smallbridge/hulls_sw/sbhullenddh.mdl",
  "models/smallbridge/hulls_sw/sbhullr.mdl",
  "models/smallbridge/hulls_sw/sbhullrdh.mdl",
  "models/smallbridge/hulls_sw/sbhullrtri.mdl",
  "models/smallbridge/hulls_sw/sbhullslanthalfl.mdl",
  "models/smallbridge/hulls_sw/sbhullslanthalfr.mdl",
  "models/smallbridge/hulls_sw/sbhullslantl.mdl",
  "models/smallbridge/hulls_sw/sbhullslantr.mdl",
  "models/smallbridge/hulls_sw/sbhullt.mdl",
  "models/smallbridge/hulls_sw/sbhulltdh.mdl",
  "models/smallbridge/hulls_sw/sbhulltdl.mdl",
  "models/smallbridge/hulls_sw/sbhulltdldw.mdl",
  "models/smallbridge/hulls_sw/sbhulltri1.mdl",
  "models/smallbridge/hulls_sw/sbhulltri2.mdl",
  "models/smallbridge/hulls_sw/sbhulltri3.mdl",
  "models/smallbridge/hulls_sw/sbhullx.mdl",
  "models/smallbridge/hulls_sw/sbhullxdh.mdl",
  "models/smallbridge/hulls_sw/sbhullxdl.mdl",
  "models/smallbridge/hulls_sw/sbhullxdldw.mdl",
}

smb_panels = {
  "models/smallbridge/panels/sbdoor.mdl",
  "models/smallbridge/panels/sbdooriris.mdl",
  "models/smallbridge/panels/sbdoorsquare.mdl",
  "models/smallbridge/panels/sbdoorwide.mdl",
  "models/smallbridge/panels/sbpaneldh.mdl",
  "models/smallbridge/panels/sbpaneldhdw.mdl",
  "models/smallbridge/panels/sbpaneldockin.mdl",
  "models/smallbridge/panels/sbpaneldockout.mdl",
  "models/smallbridge/panels/sbpaneldoor.mdl",
  "models/smallbridge/panels/sbpaneldoordw.mdl",
  "models/smallbridge/panels/sbpaneldoordw2.mdl",
  "models/smallbridge/panels/sbpaneldooriris.mdl",
  "models/smallbridge/panels/sbpaneldoorsquare.mdl",
  "models/smallbridge/panels/sbpaneldoorsquaredw.mdl",
  "models/smallbridge/panels/sbpaneldoorwide.mdl",
  "models/smallbridge/panels/sbpanelsolid.mdl",
  "models/smallbridge/panels/sbpanelsoliddw.mdl",
}

smb_ship_parts = {
  "models/smallbridge/ship parts/sbcockpit1.mdl",
  "models/smallbridge/ship parts/sbcockpit2.mdl",
  "models/smallbridge/ship parts/sbcockpit2o.mdl",
  "models/smallbridge/ship parts/sbcockpit2or.mdl",
  "models/smallbridge/ship parts/sbcockpit3.mdl",
  "models/smallbridge/ship parts/sbcockpit4.mdl",
  "models/smallbridge/ship parts/sbcockpit5dw.mdl",
  "models/smallbridge/ship parts/sbengine1.mdl",
  "models/smallbridge/ship parts/sbengine2.mdl",
  "models/smallbridge/ship parts/sbengine2o.mdl",
  "models/smallbridge/ship parts/sbengine2or.mdl",
  "models/smallbridge/ship parts/sbengine3.mdl",
  "models/smallbridge/ship parts/sbengine4dw.mdl",
  "models/smallbridge/ship parts/sbengine4l.mdl",
  "models/smallbridge/ship parts/sbengine4m.mdl",
  "models/smallbridge/ship parts/sbengine4r.mdl",
  "models/smallbridge/ship parts/sbengine5.mdl",
  "models/smallbridge/ship parts/sbengine5dwdh.mdl",
  "models/smallbridge/ship parts/sbhulldsdwe.mdl",
  "models/smallbridge/ship parts/sbhulldsdwe2.mdl",
  "models/smallbridge/ship parts/sbhulldse.mdl",
  "models/smallbridge/ship parts/sbhulldse2.mdl",
  "models/smallbridge/ship parts/sbhulldseb.mdl",
  "models/smallbridge/ship parts/sbhulldsp.mdl",
  "models/smallbridge/ship parts/sbhulldsp2.mdl",
  "models/smallbridge/ship parts/sbhulldst.mdl",
  "models/smallbridge/ship parts/sblandramp.mdl",
  "models/smallbridge/ship parts/sblandrampdw.mdl",
  "models/smallbridge/ship parts/sblandrampdwdh.mdl",
  "models/smallbridge/ship parts/sblandrampp.mdl",
  "models/smallbridge/ship parts/sblandramppdw.mdl",
  "models/smallbridge/ship parts/sblandramppdwdh.mdl",
  "models/smallbridge/ship parts/sblanduramp.mdl",
  "models/smallbridge/ship parts/sblandurampdw.mdl",
  "models/smallbridge/ship parts/sblandurampdwdh.mdl",
}

smb_ships = {
  "models/smallbridge/ships/sbshuttlec1e1.mdl",
  "models/smallbridge/ships/sbshuttlec1e2.mdl",
  "models/smallbridge/ships/sbshuttlec2e2.mdl",
  "models/smallbridge/ships/sbfrigate1.mdl",
  "models/smallbridge/ships/hysteria_galapagos.mdl",
  "models/smallbridge/ships/wilkie1020.mdl",
  "models/smallbridge/ships/steakknife.mdl",
  "models/smallbridge/ships/matthew0623_hydra.mdl",
}

smb_splitters = {
  "models/smallbridge/splitters/sbconvmb.mdl",
  "models/smallbridge/splitters/sbconvmbdh.mdl",
  "models/smallbridge/splitters/sbconvmbdw.mdl",
  "models/smallbridge/splitters/sbconvmbdwdh.mdl",
  "models/smallbridge/splitters/sbsplit2s-2sw.mdl",
  "models/smallbridge/splitters/sbsplit2s-dw.mdl",
  "models/smallbridge/splitters/sbsplitdws-dhd.mdl",
  "models/smallbridge/splitters/sbsplitdws-dhm.mdl",
  "models/smallbridge/splitters/sbsplitdws-dhu.mdl",
  "models/smallbridge/splitters/sbsplits-dhd.mdl",
  "models/smallbridge/splitters/sbsplits-dhm.mdl",
  "models/smallbridge/splitters/sbsplits-dhu.mdl",
  "models/smallbridge/splitters/sbsplits-dw.mdl",
  "models/smallbridge/splitters/sbsplits-dwa.mdl",
  "models/smallbridge/splitters/sbsplits-dwdh.mdl",
  "models/smallbridge/splitters/sbsplitv.mdl",
  "models/smallbridge/splitters/sbsplitvdh.mdl",
  "models/smallbridge/splitters/sbsplitvw.mdl",
}

smb_station_parts = {
  "models/smallbridge/station parts/sbbayaps.mdl",
  "models/smallbridge/station parts/sbbaydps.mdl",
  "models/smallbridge/station parts/sbbridgecomm.mdl",
  "models/smallbridge/station parts/sbbridgecommdw.mdl",
  "models/smallbridge/station parts/sbbridgecommelev.mdl",
  "models/smallbridge/station parts/sbbridgesphere.mdl",
  "models/smallbridge/station parts/sbbridgevisor.mdl",
  "models/smallbridge/station parts/sbbridgevisorb.mdl",
  "models/smallbridge/station parts/sbbridgevisorm.mdl",
  "models/smallbridge/station parts/sbbridgevisort.mdl",
  "models/smallbridge/station parts/sbdockcs.mdl",
  "models/smallbridge/station parts/sbhangarld.mdl",
  "models/smallbridge/station parts/sbhangarlu.mdl",
  "models/smallbridge/station parts/sbhangarlud.mdl",
  "models/smallbridge/station parts/sbhangarlud2.mdl",
  "models/smallbridge/station parts/sbhubl.mdl",
  "models/smallbridge/station parts/sbhuble.mdl",
  "models/smallbridge/station parts/sbhubls.mdl",
  "models/smallbridge/station parts/sbhubs.mdl",
  "models/smallbridge/station parts/sbrooml1.mdl",
  "models/smallbridge/station parts/sbroomsgc.mdl",
}

smb_wings_walkways_and_misc = {
  "models/smallbridge/wings/sbwingc1l.mdl",
  "models/smallbridge/wings/sbwingc1r.mdl",
  "models/smallbridge/wings/sbwingls1l.mdl",
  "models/smallbridge/wings/sbwingls1r.mdl",
  "models/smallbridge/wings/sbwingm1l.mdl",
  "models/smallbridge/wings/sbwingm1le.mdl",
  "models/smallbridge/wings/sbwingm1r.mdl",
  "models/smallbridge/wings/sbwingm1re.mdl",
  "models/smallbridge/wings/sbwings1l.mdl",
  "models/smallbridge/wings/sbwings1r.mdl",
  "models/smallbridge/walkways/sbwalkwaye.mdl",
  "models/smallbridge/walkways/sbwalkwaye2.mdl",
  "models/smallbridge/walkways/sbwalkwayr.mdl",
  "models/smallbridge/walkways/sbwalkwayt.mdl",
  "models/smallbridge/walkways/sbwalkwayx.mdl",
  "models/smallbridge/other/sbconsole.mdl",
  "models/smallbridge/other/sbconsolelow.mdl",
  "models/smallbridge/other/sbconsoletop.mdl",
 }


sbep_modellist = {
    ["SmallBridge Parts"] = {smb_elevators_large, smb_elevators_small, smb_height_transfer, smb_hulls_dw, smb_hulls_sw, smb_panels, smb_ship_parts, smb_ships, smb_splitters, smb_station_parts, smb_wings_walkways_and_misc},
    ["MedBridge Parts"] = {med_bridges, med_carrier_deck, med_doubles, med_engines, med_entry, med_hangers, med_misc, med_singles, med_triples},
    ["ModBridge Parts"] = {mod_accessories, mod_cockpits_bridges_and_glass_corridors, mod_corridor_segments, mod_corvette_fighters, mod_elevators, mod_engines_weapons_prefabs_and_doors, mod_external_decor, mod_height_transfer, mod_spartan, mod_splitters},
    ["SBMP Parts"] = {sbmp_fighters, sbmp_freighters, sbmp_ship_modules, sbmp_slyfo, sbmp_weapons},
    ["Other"] = {other_sbep_community}
}


function populateContent (viewPanel, modelTable)
  viewPanel:Clear(true)
  
  for i,j in pairs(modelTable) do
    for k,v in ipairs(j) do
  	  local cp = spawnmenu.GetContentType("model")
  	  if (cp) then
  	    cp(viewPanel, {model = v})
  	  end
    end
  end
end

function populate (nodeName, modelTable, pnlContent, masterNode, viewPanel)
  local node = masterNode:AddNode(nodeName, "icon16/folder_database.png")
  
  node.DoClick = function()
	viewPanel:Clear(true)
    populateContent(viewPanel, modelTable)
    pnlContent:SwitchPanel(viewPanel)
  end
end


hook.Add("PopulateContent", "SBEP Models", function( pnlContent, tree, node)
  local viewPanel = vgui.Create("ContentContainer", pnlContent)
  viewPanel:SetVisible(false)
  local masterNode = node:AddNode("SBEP Models", "icon16/folder_database.png")
  
  for k,v in pairs(sbep_modellist) do
    populate(k, v, pnlContent, masterNode, viewPanel)
  end
end)
